'use strict';
(() => {
 const $ = s => document.querySelector(s);
 const form=$('.editor-form'), body=$('#article-body'), source=$('#article-html');
 const fields={title:$('#article-title'),date:$('#article-date'),slug:$('#article-slug'),categories:$('#article-categories'),tags:$('#article-tags'),summary:$('#article-summary')};
 let state={articles:[],token:null,date:''}, currentId=null, published=false, mode='visual', dirty=false, storageTimer=null, range=null, insertion=null;
 const esc = text => String(text).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 const cacheKey = () => 'usagi-editor-unsaved:'+(currentId||'new');
 function snapshot(){ return {id:currentId,...Object.fromEntries(Object.entries(fields).map(([key,field])=>[key,field.value])),body:mode==='visual'?body.innerHTML:source.value}; }
 function cache(){ if(!dirty)return;try{localStorage.setItem(cacheKey(),JSON.stringify(snapshot()));$('#autosave-status').textContent='已在此瀏覽器暫存';}catch{$('#autosave-status').textContent='瀏覽器暫存已滿，請按「儲存草稿」';} }
 function changed(){dirty=true;$('#save-status').textContent='有未存回專案的修改';$('#autosave-status').textContent='正在暫存…';clearTimeout(storageTimer);storageTimer=setTimeout(cache,400);}
 function renderList(){const q=$('.editor-list-search input').value.trim().toLowerCase();const container=$('.editor-list');container.replaceChildren();state.articles.filter(a=>a.title.toLowerCase().includes(q)).forEach(a=>{const b=document.createElement('button');b.type='button';b.classList.toggle('active',a.id===currentId);const title=document.createElement('strong');title.textContent=a.title;const meta=document.createElement('span');meta.textContent=`${a.date} · ${a.status==='draft'?'草稿':'已發布'}${a.hasDraft&&a.status!=='draft'?' · 有未發布草稿':''}`;b.append(title,meta);b.addEventListener('click',()=>openArticle(a.id));container.append(b);});}
 function apply(values){Object.entries(fields).forEach(([k,v])=>{v.value=values[k]||'';});body.innerHTML=values.body||'';source.value=values.body||'';}
 function restore(){try{const raw=localStorage.getItem(cacheKey());if(raw){apply(JSON.parse(raw));dirty=true;$('#autosave-status').textContent='已恢復此瀏覽器的未儲存內容';$('#save-status').textContent='已恢復暫存，請儲存草稿或發布';}}catch{}}
 function configure(){fields.date.disabled=published;fields.slug.disabled=published;fields.slug.required=!published;$('#article-state').textContent=published?'修改已發布文章':'未發布的新文章';form.hidden=false;setMode('visual');}
 function newArticle(){cache();currentId=null;published=false;dirty=false;apply({date:state.date,slug:'note-'+state.date.replace(/-/g,'')+'-'+Math.random().toString(16).slice(2,6)});configure();$('#save-status').textContent='尚未儲存';$('#autosave-status').textContent='';restore();renderList();fields.title.focus();}
 async function api(path,payload){const response=await fetch(path,payload?{method:'POST',headers:{'Content-Type':'application/json','X-Editor-Token':state.token},body:JSON.stringify(payload)}:{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'請求未完成');return data;}
 async function refresh(){const s=await api('/api/state');state=s;renderList();}
 async function openArticle(id){cache();try{const a=await api('/api/article?id='+encodeURIComponent(id));currentId=id;published=state.articles.some(p=>p.id===id&&p.status==='published');dirty=false;apply({...a,slug:decodeURIComponent(a.url).split('/').filter(Boolean).at(-1),categories:a.categories.map(v=>v.name).join(', '),tags:a.tags.map(v=>v.name).join(', ')});configure();$('#save-status').textContent=a.status==='draft'?'已載入專案草稿':'已載入原文章，尚未修改';$('#autosave-status').textContent='';restore();renderList();fields.title.focus();}catch(e){$('#save-status').textContent=e.message;}}
 function setMode(next){if(mode===next){body.hidden=next!=='visual';source.hidden=next!=='html';return;}if(next==='html')source.value=body.innerHTML;else body.innerHTML=sanitize(source.value);mode=next;body.hidden=next!=='visual';source.hidden=next!=='html';$('.editor-toolbar').hidden=next==='html';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===next)));}
 function sanitize(html){const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,object,embed,style,link,meta,base').forEach(n=>n.remove());doc.querySelectorAll('*').forEach(n=>[...n.attributes].forEach(a=>{if(a.name.toLowerCase().startsWith('on')||(['href','src'].includes(a.name)&&/^\s*(javascript:|vbscript:|data:text\/html)/i.test(a.value)))n.removeAttribute(a.name);}));return doc.body.innerHTML;}
 function rememberRange(){const selection=window.getSelection();if(selection.rangeCount&&body.contains(selection.anchorNode))range=selection.getRangeAt(0).cloneRange();}
 function focusRange(){body.focus();if(range&&body.contains(range.commonAncestorContainer)){const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);} }
 body.addEventListener('keyup',rememberRange);body.addEventListener('mouseup',rememberRange);body.addEventListener('input',changed);source.addEventListener('input',changed);Object.values(fields).forEach(field=>field.addEventListener('input',changed));
 body.addEventListener('paste',e=>{const html=e.clipboardData.getData('text/html');if(html){e.preventDefault();document.execCommand('insertHTML',false,sanitize(html));changed();}});
 document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.mode)));
 $('.editor-toolbar').addEventListener('mousedown',e=>{if(e.target.closest('button')){e.preventDefault();rememberRange();}});
 document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>{focusRange();document.execCommand(b.dataset.command);changed();}));
 document.querySelectorAll('[data-block]').forEach(b=>b.addEventListener('click',()=>{focusRange();document.execCommand('formatBlock',false,b.dataset.block);changed();}));
 const dialog=$('.editor-insert-dialog'),value=$('#insert-value'),caption=$('#insert-caption'),code=$('#insert-code-text');
 function showInsert(kind){rememberRange();insertion=kind;value.value='';caption.value='';code.value='';$('#insert-error').textContent='';code.hidden=kind!=='code';value.hidden=kind==='code';value.required=kind!=='code';$('#insert-caption-label').hidden=kind==='code';$('#insert-title').textContent={link:'插入連結',image:'插入圖片',code:'插入程式碼'}[kind];$('#insert-label').textContent=kind==='code'?'程式碼內容（可貼上多行）':'網址';dialog.showModal();(kind==='code'?code:value).focus();}
 $('#insert-link').addEventListener('click',()=>showInsert('link'));$('#insert-image').addEventListener('click',()=>showInsert('image'));$('#insert-code').addEventListener('click',()=>showInsert('code'));$('#insert-cancel').addEventListener('click',()=>dialog.close());
 dialog.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const url=value.value.trim();if(insertion!=='code'&&!/^(https?:\/\/|\/[^/]|#|mailto:)/i.test(url)){$('#insert-error').textContent='請使用完整 HTTPS 網址、/images/ 路徑或文章錨點。';return;}const text=caption.value.trim();let html=insertion==='code'?`<figure class="highlight plaintext"><table><tbody><tr><td class="code"><pre>${esc(code.value)}</pre></td></tr></tbody></table></figure><p><br></p>`:insertion==='image'?`<p><img src="${esc(url)}" alt="${esc(text||'文章插圖')}"></p>`:`<a href="${esc(url)}">${esc(text||url)}</a>`;dialog.close();focusRange();document.execCommand('insertHTML',false,html);changed();rememberRange();});
 $('#upload-image').addEventListener('click',()=>{rememberRange();$('#image-file').click();});
 $('#image-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>5_000_000){$('#save-status').textContent='圖片需小於 5 MB。';return;}$('#save-status').textContent='正在將圖片存入專案…';try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const result=await api('/api/upload-image',{data});focusRange();document.execCommand('insertHTML',false,`<p><img src="${esc(result.url)}" alt="${esc(file.name)}"></p>`);changed();$('#save-status').textContent='圖片已加入。發布時也請上傳 images/uploads 資料夾。';}catch(err){$('#save-status').textContent=err.message||'圖片未能上傳，請重試。';}e.target.value='';});
 async function save(publish){if(!form.reportValidity())return;const buttons=[...document.querySelectorAll('.editor-save-bar button')];buttons.forEach(b=>b.disabled=true);const oldKey=cacheKey();$('#save-status').textContent=publish?'正在產生本機網站…':'正在儲存草稿…';try{const data=await api(publish?'/api/publish':'/api/save-draft',snapshot());currentId=data.id;published=publish||published;dirty=false;clearTimeout(storageTimer);localStorage.removeItem(oldKey);localStorage.removeItem(cacheKey());$('#autosave-status').textContent='已存回專案';$('#save-status').textContent=data.message;if(publish){$('#article-state').textContent='已發布到本機網站';fields.slug.disabled=true;fields.date.disabled=true;fields.slug.required=false;}await refresh();}catch(e){$('#save-status').textContent=e.message;cache();}finally{buttons.forEach(b=>b.disabled=false);}}
 $('#save-draft').addEventListener('click',()=>save(false));$('#publish-article').addEventListener('click',()=>save(true));form.addEventListener('submit',e=>e.preventDefault());$('#new-article').addEventListener('click',newArticle);$('.editor-list-search input').addEventListener('input',renderList);
 $('#preview-article').addEventListener('click',()=>{const a=snapshot(),preview=window.open('','_blank');if(!preview){$('#save-status').textContent='瀏覽器封鎖了預覽視窗，請允許此網站開啟新分頁。';return;}preview.opener=null;const html=sanitize(a.body).replace(/<(\/?)(h[1-5])\b/g,(_,slash,tag)=>'<'+slash+'h'+(Number(tag[1])+1));preview.document.write(`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(a.title||'文章預覽')}</title><link rel="stylesheet" href="${location.origin}/assets/site.css"></head><body><main class="wrap article-wrap"><p class="eyebrow">文章預覽 · 尚未更新網站</p><header class="article-heading"><h1>${esc(a.title||'尚未命名的文章')}</h1><div class="article-meta">${esc(a.date)}</div><p>${esc(a.summary)}</p></header><article class="prose" style="max-width:850px">${html}</article></main></body></html>`);preview.document.close();});
 window.addEventListener('beforeunload',e=>{if(dirty){cache();e.preventDefault();e.returnValue='';}});
 refresh().then(newArticle).catch(()=>{form.hidden=true;$('.editor-offline').hidden=false;$('#new-article').disabled=true;$('.editor-list-search input').disabled=true;$('.local-label').textContent='需要本機編輯伺服器';});
})();
